site_name: BTS CIEL Immac' 2024 - 25
site_url: https://bts-ciel-immac-laval.github.io

copyright: Copyright &copy; 2024 - 2025 Mathieu DOMER

theme:
  name: material
  language: fr
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tooltips
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Mode sombre
      primary: amber
      accent: indigo
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Mode clair
      primary: amber
      accent: indigo
  logo: assets/f11_logo.png
  favicon: assets/f11_logo.png
extra_css:
  - stylesheets/extra.css
extra:
  analytics:
    provider: google
    property: G-XVB7T4MB7D
  consent:
    title: Consentement aux cookies
    description: >- 
      Nous utilisons des cookies pour reconnaître vos visites répétées et vos préférences, ainsi que pour mesurer l'efficacité de notre documentation et pour savoir si les utilisateurs trouvent ce qu'ils recherchent. Avec votre consentement, vous nous aidez à améliorer notre application.
plugins:
  - search
  - tags
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences :
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
